title: OpenMIIR
email: sstober@uni-potsdam.de
description: > # this means to ignore newlines until "baseurl:"
  public domain data & open source code for Music Imagery Information Retrieval
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  openmiir

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-slate
#gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

